#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 0

#define VERSION_AR VERSION_MAJOR,VERSION_MINOR,VERSION_PATCH
#define STRINGIFY(s) #s
#define VERSION_STR STRINGIFY(VERSION_MAJOR.VERSION_MINOR.VERSION_PATCH)
#define VERSION VERSION_MAJOR.VERSION_MINOR
