#include "\z\lumchem\addons\main\script_version.hpp"

#define VERSION_MAJOR MAJOR
#define VERSION_MINOR MINOR
#define VERSION_PATCH PATCH

#define VERSION_AR VERSION_MAJOR,VERSION_MINOR,VERSION_PATCH
#define STRINGIFY(s) #s
#define VERSION_STR STRINGIFY(VERSION_MAJOR.VERSION_MINOR.VERSION_PATCH)
#define VERSION VERSION_MAJOR.VERSION_MINOR
